name: Android CI/CD

on:
  workflow_dispatch:
    inputs:
      artifactName:
        description: 'Name for the artifact (e.g., debug-apk-v1.0.0)'
        required: true
        default: 'debug-apk'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21.0.4'
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.9

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.artifactName }}
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 14